-- !Ups
create table GENERIC_APPLICATION_EVENTS (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    APP_NAME VARCHAR(128),
    EVENT_TYPE VARCHAR(32),
    MESSAGE VARCHAR(1024),
    RECEIVED_TIMESTAMP TIMESTAMP
);

-- !Downs
drop table GENERIC_APPLICATION_EVENTS;